name: CI/CD for academic-schedule-parser

on:
  push:
    branches: [ main, developer-parser ]
  pull_request:
    branches: [ main, developer-parser ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-testing.txt
        pip install -r requirements-dev.txt

    - name: Run tests from schedule_parser/testing
      env:
        AUTH_URL: "https://msapi.top-academy.ru/api/v2/auth/login"
        TOP_USERNAME: "Kuche_mu73"
        PASSWORD: "6C3f6G3p"
        APPLICATION_KEY: "6a56a5df2667e65aab73ce76d1dd737f7d1faef9c52e8b8c55ac75f565d8e8a6"
        SCHEDULE_URL: "https://msapi.top-academy.ru/api/v2/schedule/operations/get-month?date_filter="
        ID_CITY: "592"
      run: |
        pytest schedule_parser/testing/test_auth.py -v
        pytest schedule_parser/testing/test_post_request.py -v

    - name: Run tests configs
      env:
        AUTH_URL: "https://msapi.top-academy.ru/api/v2/auth/login"
        TOP_USERNAME: "Kuche_mu73"
        PASSWORD: "6C3f6G3p"
        APPLICATION_KEY: "6a56a5df2667e65aab73ce76d1dd737f7d1faef9c52e8b8c55ac75f565d8e8a6"
      run: |
        pytest testing_configs/test_config_user.py -v
